[package]
name = "aestra-bevy"
description = "Bevy integration and reference playback runtime for Aestra effects"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
aestra-bevy-render = { path = "../../crates/aestra-bevy-render" }
aestra-compiler = { path = "../../crates/aestra-compiler" }
aestra-core = { path = "../../crates/aestra-core" }
aestra-runtime = { path = "../../crates/aestra-runtime" }
bevy.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
aestra-artifact = { path = "../../crates/aestra-artifact" }
wesl = "0.3.2"
